server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/strong
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
